### ISSUE TITLE
ios image auto is not working?

### ISSUE THREAD

**Issue by k-inoway** [danielpaulus/go-ios#120] opened 2022-04-15 01:53 UTC
**Describe the bug**
 `ios image auto` This command did not download the developer disk image.
I opened the direct download link and it downloaded successfully, so it does not appear to be a broken link.

**To Reproduce**
1. Run command. `ios image auto`
2. Error shown in screenshot. `"failed downloading image: image not found"`

**Expected behavior**
A developer disk image is downloaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/40589931/163503881-0a6e339f-4cfc-466d-ac0e-c377ffe222ca.png)

**Desktop:**
 - OS: Windows10 20H2

**Smartphone:**
 - Device: iPhone6 and iPhone6S
 - OS: iOS 12.1.4 and 15.0.2

**Comment by danielpaulus** [comment] 2022-04-15 07:10
Could it be that it happens because of  `\` backlashes somewhere? 🤔 
I really need a windows VM to test this stuff 😓 
Let me set that up and see if I can reproduce this behavior.

**Comment by shamanec** [comment] 2022-04-21 14:40
#129 I've created a PR to fix that :)

**Comment by danielpaulus** [comment] 2022-04-24 19:25
this should be fixed now.

**Closed by danielpaulus** 2022-04-24 19:25 UTC
